branches:
  only:
  - master
language: python
python: 3.6
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --acl public-read --delete . s3://lunchbuddies.quinnweber.com
- aws configure set preview.cloudfront true
- aws cloudfront create-invalidation --distribution-id E3TB6WBWJWWQF1 --paths '/*'
