branches:
  only:
  - master
language: python
python: 3.6
install: pip install awscli
script:
- npm run build
- npm run export
- aws s3 sync --acl public-read --delete ./out s3://next.quinnweber.com
- test $TRAVIS_BRANCH = "master" && aws s3 sync --acl public-read --delete ./out s3://lunchbuddies.quinnweber.com
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id E3TB6WBWJWWQF1 --paths '/*'
