branches:
  only:
  - master
language: python
python: 3.6
install: pip install awscli
script:
- aws s3 sync --exclude '.git/*' --exclude 'README.md' --exclude '.travis.yml' --acl public-read --delete . s3://lunchbuddies.quinnweber.com
